### ISSUE TITLE
Crash with Matrix is Singular Error

### ISSUE THREAD

**Issue by mrsolt** [JeffersonLab/hps-java#426] opened 2019-04-08 18:25 UTC
We have seen this issue before, where a track can't find one of the hits during the GBL refit and then crashes. I found the place to patch this. Easy fix.

**Comment by JeremyMcCormick** [comment] 2019-04-09 05:13
This is a duplicate of #416 so I'm closing (use the previously created issue).

**Comment by JeremyMcCormick** [comment] 2019-04-09 05:17
oops

**Comment by JeremyMcCormick** [comment] 2019-04-10 06:49
Resolved by PR #428.

**Closed as completed by JeremyMcCormick** 2019-04-10 06:49 UTC
Labels: bug
