### ISSUE TITLE
Maximum raw tracker hits per event

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#271] opened 2017-12-08 20:35 UTC
adds a cut to the RawTrackerHitFitterDriver, causing it to skip an event if there are more than _maxRawHits_ raw tracker hits in the event.  Also adding a setter for this value.  

Tentatively, I am setting the default value of _maxRawHits_ to 300.  This cuts out about 0.3% of good trident events in both 2015 and 2016 datasets.

**Comment by mholtrop** [comment] 2017-12-11 01:02
This is a duplicate of #267

**Closed as completed** 2017-12-12 23:03 UTC
